# Generated by Django 3.2.3 on 2024-02-03 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=40, unique=True, verbose_name='id')),
                ('width', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Ширина поля')),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Высота поля')),
                ('mines_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество мин')),
                ('completed', models.BooleanField(default=False)),
                ('field', models.CharField(max_length=900, verbose_name='Хранимое поле игры')),
                ('open_field', models.CharField(max_length=900, verbose_name='Поле доступное игроку')),
            ],
            options={
                'verbose_name': 'Сохраненная игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
